# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.fee import Fee

class TestFee(unittest.TestCase):
    """Fee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Fee:
        """Test Fee
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Fee`
        """
        model = Fee()
        if include_optional:
            return Fee(
                gross = 0,
                discount = 0,
                net = 0,
                breakdown = [
                    maytes_api_client.models.fee_breakdown_line.FeeBreakdownLine(
                        type = 'rate_card', 
                        id = '', 
                        label = '', 
                        amount = 56, )
                    ]
            )
        else:
            return Fee(
                gross = 0,
                discount = 0,
                net = 0,
                breakdown = [
                    maytes_api_client.models.fee_breakdown_line.FeeBreakdownLine(
                        type = 'rate_card', 
                        id = '', 
                        label = '', 
                        amount = 56, )
                    ],
        )
        """

    def testFee(self):
        """Test Fee"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
