# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.create_checkout_request import CreateCheckoutRequest

class TestCreateCheckoutRequest(unittest.TestCase):
    """CreateCheckoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCheckoutRequest:
        """Test CreateCheckoutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCheckoutRequest`
        """
        model = CreateCheckoutRequest()
        if include_optional:
            return CreateCheckoutRequest(
                merchant_order_id = '',
                merchant_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_amount = 0,
                currency = 'AEI',
                return_url = '',
                cancel_url = '',
                items = [
                    null
                    ],
                fees = [
                    maytes_api_client.models.checkout_fee.CheckoutFee(
                        name = '0', 
                        description = '', 
                        fee_type = 'refund_protection', 
                        scope = 'cart', 
                        amount = 0, 
                        currency = 'AEI', 
                        metadata = {
                            'key' : null
                            }, 
                        applies_to = [
                            ''
                            ], )
                    ],
                discounts = [
                    maytes_api_client.models.checkout_discount.CheckoutDiscount(
                        name = '0', 
                        description = '', 
                        scope = 'cart', 
                        amount = 0, 
                        currency = 'AEI', 
                        metadata = {
                            'key' : null
                            }, 
                        applies_to = [
                            ''
                            ], )
                    ],
                tax = maytes_api_client.models.tax.Tax(
                    amount = 0, 
                    percentage = '4', 
                    inclusive = True, ),
                shipping_amount = 0,
                customer_data = maytes_api_client.models.customer_data.CustomerData(
                    name = '', 
                    mobile = '', 
                    email = '', ),
                metadata = {
                    'key' : null
                    },
                allocation_model = 'basic_amount'
            )
        else:
            return CreateCheckoutRequest(
                total_amount = 0,
                currency = 'AEI',
                return_url = '',
                cancel_url = '',
                items = [
                    null
                    ],
        )
        """

    def testCreateCheckoutRequest(self):
        """Test CreateCheckoutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
