# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.checkout_discount import CheckoutDiscount

class TestCheckoutDiscount(unittest.TestCase):
    """CheckoutDiscount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutDiscount:
        """Test CheckoutDiscount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutDiscount`
        """
        model = CheckoutDiscount()
        if include_optional:
            return CheckoutDiscount(
                name = '0',
                description = '',
                scope = 'cart',
                amount = 0,
                currency = 'AEI',
                metadata = {
                    'key' : null
                    },
                applies_to = [
                    ''
                    ]
            )
        else:
            return CheckoutDiscount(
                name = '0',
                scope = 'cart',
                amount = 0,
                currency = 'AEI',
        )
        """

    def testCheckoutDiscount(self):
        """Test CheckoutDiscount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
