# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.create_checkout409_response import CreateCheckout409Response

class TestCreateCheckout409Response(unittest.TestCase):
    """CreateCheckout409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCheckout409Response:
        """Test CreateCheckout409Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCheckout409Response`
        """
        model = CreateCheckout409Response()
        if include_optional:
            return CreateCheckout409Response(
                message = '',
                error = '',
                code = 'order_already_authorized',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return CreateCheckout409Response(
                message = '',
                error = '',
                code = 'order_already_authorized',
        )
        """

    def testCreateCheckout409Response(self):
        """Test CreateCheckout409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
