# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.food_beverage_line_item import FoodBeverageLineItem

class TestFoodBeverageLineItem(unittest.TestCase):
    """FoodBeverageLineItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoodBeverageLineItem:
        """Test FoodBeverageLineItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FoodBeverageLineItem`
        """
        model = FoodBeverageLineItem()
        if include_optional:
            return FoodBeverageLineItem(
                item_ref = '0',
                parent_ref = '',
                sku = '',
                name = '0',
                description = '',
                image_url = '',
                quantity = 0,
                unit_price = 0,
                currency = 'AEI',
                category = 'food_beverage'
            )
        else:
            return FoodBeverageLineItem(
                item_ref = '0',
                name = '0',
                quantity = 0,
                unit_price = 0,
                currency = 'AEI',
                category = 'food_beverage',
        )
        """

    def testFoodBeverageLineItem(self):
        """Test FoodBeverageLineItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
