# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.get_checkout_response import GetCheckoutResponse

class TestGetCheckoutResponse(unittest.TestCase):
    """GetCheckoutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCheckoutResponse:
        """Test GetCheckoutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCheckoutResponse`
        """
        model = GetCheckoutResponse()
        if include_optional:
            return GetCheckoutResponse(
                data = maytes_api_client.models.checkout.Checkout(
                    checkout_uuid = '', 
                    merchant_order_id = '', 
                    status = '', 
                    transaction_ref = '', 
                    checkout_url = '', 
                    merchant_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    captured_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    return_url = '', 
                    cancel_url = '', 
                    amount = 56, 
                    currency = '', 
                    service_fee = maytes_api_client.models.fee.Fee(
                        gross = 0, 
                        discount = 0, 
                        net = 0, 
                        breakdown = [
                            maytes_api_client.models.fee_breakdown_line.FeeBreakdownLine(
                                type = 'rate_card', 
                                id = '', 
                                label = '', 
                                amount = 56, )
                            ], ), 
                    refunded_amount = 0, 
                    merchant_processor_fee = 0, 
                    merchant_service_fee = 0, 
                    last_refund_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GetCheckoutResponse(
                data = maytes_api_client.models.checkout.Checkout(
                    checkout_uuid = '', 
                    merchant_order_id = '', 
                    status = '', 
                    transaction_ref = '', 
                    checkout_url = '', 
                    merchant_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    captured_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    return_url = '', 
                    cancel_url = '', 
                    amount = 56, 
                    currency = '', 
                    service_fee = maytes_api_client.models.fee.Fee(
                        gross = 0, 
                        discount = 0, 
                        net = 0, 
                        breakdown = [
                            maytes_api_client.models.fee_breakdown_line.FeeBreakdownLine(
                                type = 'rate_card', 
                                id = '', 
                                label = '', 
                                amount = 56, )
                            ], ), 
                    refunded_amount = 0, 
                    merchant_processor_fee = 0, 
                    merchant_service_fee = 0, 
                    last_refund_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testGetCheckoutResponse(self):
        """Test GetCheckoutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
