# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.o_auth_token_request import OAuthTokenRequest

class TestOAuthTokenRequest(unittest.TestCase):
    """OAuthTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuthTokenRequest:
        """Test OAuthTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuthTokenRequest`
        """
        model = OAuthTokenRequest()
        if include_optional:
            return OAuthTokenRequest(
                grant_type = '0',
                client_id = '',
                client_secret = '',
                username = '',
                password = '',
                refresh_token = '',
                scope = ''
            )
        else:
            return OAuthTokenRequest(
                grant_type = '0',
                client_id = '',
        )
        """

    def testOAuthTokenRequest(self):
        """Test OAuthTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
