# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.cancel_checkout409_response import CancelCheckout409Response

class TestCancelCheckout409Response(unittest.TestCase):
    """CancelCheckout409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CancelCheckout409Response:
        """Test CancelCheckout409Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CancelCheckout409Response`
        """
        model = CancelCheckout409Response()
        if include_optional:
            return CancelCheckout409Response(
                message = '',
                error = '',
                code = 'session_not_voidable',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return CancelCheckout409Response(
                message = '',
                error = '',
                code = 'session_not_voidable',
        )
        """

    def testCancelCheckout409Response(self):
        """Test CancelCheckout409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
