# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.capture_checkout409_response import CaptureCheckout409Response

class TestCaptureCheckout409Response(unittest.TestCase):
    """CaptureCheckout409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaptureCheckout409Response:
        """Test CaptureCheckout409Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaptureCheckout409Response`
        """
        model = CaptureCheckout409Response()
        if include_optional:
            return CaptureCheckout409Response(
                message = '',
                error = '',
                code = 'not_capturable',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return CaptureCheckout409Response(
                message = '',
                error = '',
                code = 'not_capturable',
        )
        """

    def testCaptureCheckout409Response(self):
        """Test CaptureCheckout409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
