# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.ticket_line_item import TicketLineItem

class TestTicketLineItem(unittest.TestCase):
    """TicketLineItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TicketLineItem:
        """Test TicketLineItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TicketLineItem`
        """
        model = TicketLineItem()
        if include_optional:
            return TicketLineItem(
                item_ref = '0',
                parent_ref = '',
                sku = '',
                name = '0',
                description = '',
                image_url = '',
                quantity = 0,
                unit_price = 0,
                currency = 'AEI',
                category = 'ticket',
                custom_data = maytes_api_client.models.ticket_custom_data.TicketCustomData(
                    event_id = '', 
                    event_start_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    timezone = '', 
                    ticket_class = '', 
                    name = '', 
                    event_end_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    delivery_mode = 'email', 
                    venue_name = '', 
                    venue_address = {
                        'key' : null
                        }, 
                    seating = maytes_api_client.models.ticket_seating.TicketSeating(
                        section = '', 
                        row = '', 
                        seat = '', 
                        allocation = {
                            'key' : null
                            }, ), 
                    terms_url = '', 
                    attendee_required = True, )
            )
        else:
            return TicketLineItem(
                item_ref = '0',
                name = '0',
                quantity = 0,
                unit_price = 0,
                currency = 'AEI',
                category = 'ticket',
                custom_data = maytes_api_client.models.ticket_custom_data.TicketCustomData(
                    event_id = '', 
                    event_start_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    timezone = '', 
                    ticket_class = '', 
                    name = '', 
                    event_end_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    delivery_mode = 'email', 
                    venue_name = '', 
                    venue_address = {
                        'key' : null
                        }, 
                    seating = maytes_api_client.models.ticket_seating.TicketSeating(
                        section = '', 
                        row = '', 
                        seat = '', 
                        allocation = {
                            'key' : null
                            }, ), 
                    terms_url = '', 
                    attendee_required = True, ),
        )
        """

    def testTicketLineItem(self):
        """Test TicketLineItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
