# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.ticket_seating import TicketSeating

class TestTicketSeating(unittest.TestCase):
    """TicketSeating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TicketSeating:
        """Test TicketSeating
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TicketSeating`
        """
        model = TicketSeating()
        if include_optional:
            return TicketSeating(
                section = '',
                row = '',
                seat = '',
                allocation = {
                    'key' : null
                    }
            )
        else:
            return TicketSeating(
        )
        """

    def testTicketSeating(self):
        """Test TicketSeating"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
