# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.refund_checkout402_response import RefundCheckout402Response

class TestRefundCheckout402Response(unittest.TestCase):
    """RefundCheckout402Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundCheckout402Response:
        """Test RefundCheckout402Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundCheckout402Response`
        """
        model = RefundCheckout402Response()
        if include_optional:
            return RefundCheckout402Response(
                message = '',
                error = '',
                code = 'refund_insufficient_funds',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return RefundCheckout402Response(
                message = '',
                error = '',
                code = 'refund_insufficient_funds',
        )
        """

    def testRefundCheckout402Response(self):
        """Test RefundCheckout402Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
