# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.create_refund_request import CreateRefundRequest

class TestCreateRefundRequest(unittest.TestCase):
    """CreateRefundRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRefundRequest:
        """Test CreateRefundRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRefundRequest`
        """
        model = CreateRefundRequest()
        if include_optional:
            return CreateRefundRequest(
                reason = '',
                merchant_refund_ref = '0'
            )
        else:
            return CreateRefundRequest(
                merchant_refund_ref = '0',
        )
        """

    def testCreateRefundRequest(self):
        """Test CreateRefundRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
