# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_checkout(self) -> None:
        """Test case for cancel_checkout

        Cancel authorized checkout
        """
        pass

    def test_capture_checkout(self) -> None:
        """Test case for capture_checkout

        Capture authorized checkout
        """
        pass

    def test_create_checkout(self) -> None:
        """Test case for create_checkout

        Create a new checkout
        """
        pass

    def test_get_checkout(self) -> None:
        """Test case for get_checkout

        Get checkout details
        """
        pass

    def test_get_health(self) -> None:
        """Test case for get_health

        Health check
        """
        pass

    def test_get_o_auth_token(self) -> None:
        """Test case for get_o_auth_token

        Issue an access token
        """
        pass

    def test_get_settlement(self) -> None:
        """Test case for get_settlement

        Get a settlement by UUID
        """
        pass

    def test_list_settlements(self) -> None:
        """Test case for list_settlements

        List settlements for this merchant
        """
        pass

    def test_refund_checkout(self) -> None:
        """Test case for refund_checkout

        Refund a captured checkout
        """
        pass


if __name__ == '__main__':
    unittest.main()
