# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from maytes_api_client.models.get_checkout422_response import GetCheckout422Response

class TestGetCheckout422Response(unittest.TestCase):
    """GetCheckout422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCheckout422Response:
        """Test GetCheckout422Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCheckout422Response`
        """
        model = GetCheckout422Response()
        if include_optional:
            return GetCheckout422Response(
                message = '',
                error = '',
                code = 'order_mismatch',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return GetCheckout422Response(
                message = '',
                error = '',
                code = 'order_mismatch',
        )
        """

    def testGetCheckout422Response(self):
        """Test GetCheckout422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
