# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from maytes_api_client.models.fee import Fee
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Checkout(BaseModel):
    """
    Checkout
    """ # noqa: E501
    checkout_uuid: StrictStr
    merchant_order_id: Optional[StrictStr]
    status: StrictStr
    transaction_ref: Optional[StrictStr]
    checkout_url: StrictStr
    merchant_expires_at: Optional[datetime]
    captured_at: Optional[datetime]
    return_url: Optional[StrictStr]
    cancel_url: Optional[StrictStr]
    amount: StrictInt
    currency: StrictStr
    service_fee: Fee
    refunded_amount: Annotated[int, Field(strict=True, ge=0)]
    merchant_processor_fee: Annotated[int, Field(strict=True, ge=0)]
    merchant_service_fee: Annotated[int, Field(strict=True, ge=0)]
    last_refund_at: Optional[datetime]
    __properties: ClassVar[List[str]] = ["checkout_uuid", "merchant_order_id", "status", "transaction_ref", "checkout_url", "merchant_expires_at", "captured_at", "return_url", "cancel_url", "amount", "currency", "service_fee", "refunded_amount", "merchant_processor_fee", "merchant_service_fee", "last_refund_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Checkout from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of service_fee
        if self.service_fee:
            _dict['service_fee'] = self.service_fee.to_dict()
        # set to None if merchant_order_id (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_order_id is None and "merchant_order_id" in self.model_fields_set:
            _dict['merchant_order_id'] = None

        # set to None if transaction_ref (nullable) is None
        # and model_fields_set contains the field
        if self.transaction_ref is None and "transaction_ref" in self.model_fields_set:
            _dict['transaction_ref'] = None

        # set to None if merchant_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_expires_at is None and "merchant_expires_at" in self.model_fields_set:
            _dict['merchant_expires_at'] = None

        # set to None if captured_at (nullable) is None
        # and model_fields_set contains the field
        if self.captured_at is None and "captured_at" in self.model_fields_set:
            _dict['captured_at'] = None

        # set to None if return_url (nullable) is None
        # and model_fields_set contains the field
        if self.return_url is None and "return_url" in self.model_fields_set:
            _dict['return_url'] = None

        # set to None if cancel_url (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_url is None and "cancel_url" in self.model_fields_set:
            _dict['cancel_url'] = None

        # set to None if last_refund_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_refund_at is None and "last_refund_at" in self.model_fields_set:
            _dict['last_refund_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Checkout from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checkout_uuid": obj.get("checkout_uuid"),
            "merchant_order_id": obj.get("merchant_order_id"),
            "status": obj.get("status"),
            "transaction_ref": obj.get("transaction_ref"),
            "checkout_url": obj.get("checkout_url"),
            "merchant_expires_at": obj.get("merchant_expires_at"),
            "captured_at": obj.get("captured_at"),
            "return_url": obj.get("return_url"),
            "cancel_url": obj.get("cancel_url"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "service_fee": Fee.from_dict(obj["service_fee"]) if obj.get("service_fee") is not None else None,
            "refunded_amount": obj.get("refunded_amount"),
            "merchant_processor_fee": obj.get("merchant_processor_fee"),
            "merchant_service_fee": obj.get("merchant_service_fee"),
            "last_refund_at": obj.get("last_refund_at")
        })
        return _obj


