# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from maytes_api_client.models.checkout_discount import CheckoutDiscount
from maytes_api_client.models.checkout_fee import CheckoutFee
from maytes_api_client.models.customer_data import CustomerData
from maytes_api_client.models.line_item import LineItem
from maytes_api_client.models.tax import Tax
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateCheckoutRequest(BaseModel):
    """
    CreateCheckoutRequest
    """ # noqa: E501
    merchant_order_id: Optional[StrictStr] = None
    merchant_expires_at: Optional[datetime] = None
    total_amount: Annotated[int, Field(strict=True, gt=0)]
    currency: Annotated[str, Field(strict=True)]
    return_url: StrictStr
    cancel_url: StrictStr
    items: Annotated[List[LineItem], Field(min_length=1)]
    fees: Optional[List[CheckoutFee]] = None
    discounts: Optional[List[CheckoutDiscount]] = None
    tax: Optional[Tax] = None
    shipping_amount: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    customer_data: Optional[CustomerData] = None
    metadata: Optional[Dict[str, Any]] = None
    allocation_model: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["merchant_order_id", "merchant_expires_at", "total_amount", "currency", "return_url", "cancel_url", "items", "fees", "discounts", "tax", "shipping_amount", "customer_data", "metadata", "allocation_model"]

    @field_validator('currency')
    def currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Z]{3}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{3}$/")
        return value

    @field_validator('allocation_model')
    def allocation_model_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['basic_amount', 'item_assignment']):
            raise ValueError("must be one of enum values ('basic_amount', 'item_assignment')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCheckoutRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fees (list)
        _items = []
        if self.fees:
            for _item_fees in self.fees:
                if _item_fees:
                    _items.append(_item_fees.to_dict())
            _dict['fees'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in discounts (list)
        _items = []
        if self.discounts:
            for _item_discounts in self.discounts:
                if _item_discounts:
                    _items.append(_item_discounts.to_dict())
            _dict['discounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of tax
        if self.tax:
            _dict['tax'] = self.tax.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customer_data
        if self.customer_data:
            _dict['customer_data'] = self.customer_data.to_dict()
        # set to None if merchant_order_id (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_order_id is None and "merchant_order_id" in self.model_fields_set:
            _dict['merchant_order_id'] = None

        # set to None if merchant_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_expires_at is None and "merchant_expires_at" in self.model_fields_set:
            _dict['merchant_expires_at'] = None

        # set to None if fees (nullable) is None
        # and model_fields_set contains the field
        if self.fees is None and "fees" in self.model_fields_set:
            _dict['fees'] = None

        # set to None if discounts (nullable) is None
        # and model_fields_set contains the field
        if self.discounts is None and "discounts" in self.model_fields_set:
            _dict['discounts'] = None

        # set to None if tax (nullable) is None
        # and model_fields_set contains the field
        if self.tax is None and "tax" in self.model_fields_set:
            _dict['tax'] = None

        # set to None if shipping_amount (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_amount is None and "shipping_amount" in self.model_fields_set:
            _dict['shipping_amount'] = None

        # set to None if customer_data (nullable) is None
        # and model_fields_set contains the field
        if self.customer_data is None and "customer_data" in self.model_fields_set:
            _dict['customer_data'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if allocation_model (nullable) is None
        # and model_fields_set contains the field
        if self.allocation_model is None and "allocation_model" in self.model_fields_set:
            _dict['allocation_model'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCheckoutRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchant_order_id": obj.get("merchant_order_id"),
            "merchant_expires_at": obj.get("merchant_expires_at"),
            "total_amount": obj.get("total_amount"),
            "currency": obj.get("currency"),
            "return_url": obj.get("return_url"),
            "cancel_url": obj.get("cancel_url"),
            "items": [LineItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "fees": [CheckoutFee.from_dict(_item) for _item in obj["fees"]] if obj.get("fees") is not None else None,
            "discounts": [CheckoutDiscount.from_dict(_item) for _item in obj["discounts"]] if obj.get("discounts") is not None else None,
            "tax": Tax.from_dict(obj["tax"]) if obj.get("tax") is not None else None,
            "shipping_amount": obj.get("shipping_amount"),
            "customer_data": CustomerData.from_dict(obj["customer_data"]) if obj.get("customer_data") is not None else None,
            "metadata": obj.get("metadata"),
            "allocation_model": obj.get("allocation_model")
        })
        return _obj


