# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DonationLineItem(BaseModel):
    """
    DonationLineItem
    """ # noqa: E501
    item_ref: Annotated[str, Field(min_length=1, strict=True)]
    parent_ref: Optional[StrictStr] = None
    sku: Optional[StrictStr] = None
    name: Annotated[str, Field(min_length=1, strict=True)]
    description: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    quantity: Annotated[int, Field(strict=True, gt=0)]
    unit_price: Annotated[int, Field(strict=True, ge=0)]
    currency: Annotated[str, Field(strict=True)]
    category: StrictStr
    __properties: ClassVar[List[str]] = ["item_ref", "parent_ref", "sku", "name", "description", "image_url", "quantity", "unit_price", "currency", "category"]

    @field_validator('currency')
    def currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Z]{3}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{3}$/")
        return value

    @field_validator('category')
    def category_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['donation']):
            raise ValueError("must be one of enum values ('donation')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DonationLineItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if parent_ref (nullable) is None
        # and model_fields_set contains the field
        if self.parent_ref is None and "parent_ref" in self.model_fields_set:
            _dict['parent_ref'] = None

        # set to None if sku (nullable) is None
        # and model_fields_set contains the field
        if self.sku is None and "sku" in self.model_fields_set:
            _dict['sku'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['image_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DonationLineItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_ref": obj.get("item_ref"),
            "parent_ref": obj.get("parent_ref"),
            "sku": obj.get("sku"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "image_url": obj.get("image_url"),
            "quantity": obj.get("quantity"),
            "unit_price": obj.get("unit_price"),
            "currency": obj.get("currency"),
            "category": obj.get("category")
        })
        return _obj


