# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from maytes_api_client.models.digital_goods_line_item import DigitalGoodsLineItem
from maytes_api_client.models.donation_line_item import DonationLineItem
from maytes_api_client.models.food_beverage_line_item import FoodBeverageLineItem
from maytes_api_client.models.other_line_item import OtherLineItem
from maytes_api_client.models.physical_goods_line_item import PhysicalGoodsLineItem
from maytes_api_client.models.service_line_item import ServiceLineItem
from maytes_api_client.models.ticket_line_item import TicketLineItem
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

LINEITEM_ONE_OF_SCHEMAS = ["DigitalGoodsLineItem", "DonationLineItem", "FoodBeverageLineItem", "OtherLineItem", "PhysicalGoodsLineItem", "ServiceLineItem", "TicketLineItem"]

class LineItem(BaseModel):
    """
    LineItem
    """
    # data type: TicketLineItem
    oneof_schema_1_validator: Optional[TicketLineItem] = None
    # data type: PhysicalGoodsLineItem
    oneof_schema_2_validator: Optional[PhysicalGoodsLineItem] = None
    # data type: ServiceLineItem
    oneof_schema_3_validator: Optional[ServiceLineItem] = None
    # data type: DigitalGoodsLineItem
    oneof_schema_4_validator: Optional[DigitalGoodsLineItem] = None
    # data type: FoodBeverageLineItem
    oneof_schema_5_validator: Optional[FoodBeverageLineItem] = None
    # data type: DonationLineItem
    oneof_schema_6_validator: Optional[DonationLineItem] = None
    # data type: OtherLineItem
    oneof_schema_7_validator: Optional[OtherLineItem] = None
    actual_instance: Optional[Union[DigitalGoodsLineItem, DonationLineItem, FoodBeverageLineItem, OtherLineItem, PhysicalGoodsLineItem, ServiceLineItem, TicketLineItem]] = None
    one_of_schemas: Set[str] = { "DigitalGoodsLineItem", "DonationLineItem", "FoodBeverageLineItem", "OtherLineItem", "PhysicalGoodsLineItem", "ServiceLineItem", "TicketLineItem" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = LineItem.model_construct()
        error_messages = []
        match = 0
        # validate data type: TicketLineItem
        if not isinstance(v, TicketLineItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TicketLineItem`")
        else:
            match += 1
        # validate data type: PhysicalGoodsLineItem
        if not isinstance(v, PhysicalGoodsLineItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PhysicalGoodsLineItem`")
        else:
            match += 1
        # validate data type: ServiceLineItem
        if not isinstance(v, ServiceLineItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ServiceLineItem`")
        else:
            match += 1
        # validate data type: DigitalGoodsLineItem
        if not isinstance(v, DigitalGoodsLineItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DigitalGoodsLineItem`")
        else:
            match += 1
        # validate data type: FoodBeverageLineItem
        if not isinstance(v, FoodBeverageLineItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FoodBeverageLineItem`")
        else:
            match += 1
        # validate data type: DonationLineItem
        if not isinstance(v, DonationLineItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DonationLineItem`")
        else:
            match += 1
        # validate data type: OtherLineItem
        if not isinstance(v, OtherLineItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OtherLineItem`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in LineItem with oneOf schemas: DigitalGoodsLineItem, DonationLineItem, FoodBeverageLineItem, OtherLineItem, PhysicalGoodsLineItem, ServiceLineItem, TicketLineItem. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in LineItem with oneOf schemas: DigitalGoodsLineItem, DonationLineItem, FoodBeverageLineItem, OtherLineItem, PhysicalGoodsLineItem, ServiceLineItem, TicketLineItem. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into TicketLineItem
        try:
            instance.actual_instance = TicketLineItem.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PhysicalGoodsLineItem
        try:
            instance.actual_instance = PhysicalGoodsLineItem.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ServiceLineItem
        try:
            instance.actual_instance = ServiceLineItem.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DigitalGoodsLineItem
        try:
            instance.actual_instance = DigitalGoodsLineItem.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FoodBeverageLineItem
        try:
            instance.actual_instance = FoodBeverageLineItem.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DonationLineItem
        try:
            instance.actual_instance = DonationLineItem.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OtherLineItem
        try:
            instance.actual_instance = OtherLineItem.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into LineItem with oneOf schemas: DigitalGoodsLineItem, DonationLineItem, FoodBeverageLineItem, OtherLineItem, PhysicalGoodsLineItem, ServiceLineItem, TicketLineItem. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into LineItem with oneOf schemas: DigitalGoodsLineItem, DonationLineItem, FoodBeverageLineItem, OtherLineItem, PhysicalGoodsLineItem, ServiceLineItem, TicketLineItem. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], DigitalGoodsLineItem, DonationLineItem, FoodBeverageLineItem, OtherLineItem, PhysicalGoodsLineItem, ServiceLineItem, TicketLineItem]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


