# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Settlement(BaseModel):
    """
    Settlement
    """ # noqa: E501
    uuid: UUID
    merchant_uuid: UUID
    period_from: datetime
    period_to: datetime
    idempotency_key: StrictStr
    merchant_payable_amount: StrictInt
    settled_amount: StrictInt
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)]
    status: StrictStr
    stripe_transfer_id: Optional[StrictStr]
    notes: Optional[StrictStr]
    settled_at: Optional[datetime]
    expires_at: Optional[datetime]
    reviewed_by_user_uuid: Optional[UUID]
    reviewed_at: Optional[datetime]
    rejection_reason: Optional[StrictStr]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["uuid", "merchant_uuid", "period_from", "period_to", "idempotency_key", "merchant_payable_amount", "settled_amount", "currency", "status", "stripe_transfer_id", "notes", "settled_at", "expires_at", "reviewed_by_user_uuid", "reviewed_at", "rejection_reason", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Settlement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if stripe_transfer_id (nullable) is None
        # and model_fields_set contains the field
        if self.stripe_transfer_id is None and "stripe_transfer_id" in self.model_fields_set:
            _dict['stripe_transfer_id'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if settled_at (nullable) is None
        # and model_fields_set contains the field
        if self.settled_at is None and "settled_at" in self.model_fields_set:
            _dict['settled_at'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if reviewed_by_user_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.reviewed_by_user_uuid is None and "reviewed_by_user_uuid" in self.model_fields_set:
            _dict['reviewed_by_user_uuid'] = None

        # set to None if reviewed_at (nullable) is None
        # and model_fields_set contains the field
        if self.reviewed_at is None and "reviewed_at" in self.model_fields_set:
            _dict['reviewed_at'] = None

        # set to None if rejection_reason (nullable) is None
        # and model_fields_set contains the field
        if self.rejection_reason is None and "rejection_reason" in self.model_fields_set:
            _dict['rejection_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Settlement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "merchant_uuid": obj.get("merchant_uuid"),
            "period_from": obj.get("period_from"),
            "period_to": obj.get("period_to"),
            "idempotency_key": obj.get("idempotency_key"),
            "merchant_payable_amount": obj.get("merchant_payable_amount"),
            "settled_amount": obj.get("settled_amount"),
            "currency": obj.get("currency"),
            "status": obj.get("status"),
            "stripe_transfer_id": obj.get("stripe_transfer_id"),
            "notes": obj.get("notes"),
            "settled_at": obj.get("settled_at"),
            "expires_at": obj.get("expires_at"),
            "reviewed_by_user_uuid": obj.get("reviewed_by_user_uuid"),
            "reviewed_at": obj.get("reviewed_at"),
            "rejection_reason": obj.get("rejection_reason"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


