# coding: utf-8

"""
    Maytes API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from maytes_api_client.models.ticket_seating import TicketSeating
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TicketCustomData(BaseModel):
    """
    TicketCustomData
    """ # noqa: E501
    event_id: StrictStr
    event_start_at: datetime
    timezone: StrictStr
    ticket_class: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    event_end_at: Optional[datetime] = None
    delivery_mode: Optional[StrictStr] = None
    venue_name: Optional[StrictStr] = None
    venue_address: Optional[Dict[str, Any]] = None
    seating: Optional[TicketSeating] = None
    terms_url: Optional[StrictStr] = None
    attendee_required: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["event_id", "event_start_at", "timezone", "ticket_class", "name", "event_end_at", "delivery_mode", "venue_name", "venue_address", "seating", "terms_url", "attendee_required"]

    @field_validator('delivery_mode')
    def delivery_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['email', 'sms', 'post', 'at_venue']):
            raise ValueError("must be one of enum values ('email', 'sms', 'post', 'at_venue')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TicketCustomData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of seating
        if self.seating:
            _dict['seating'] = self.seating.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TicketCustomData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_id": obj.get("event_id"),
            "event_start_at": obj.get("event_start_at"),
            "timezone": obj.get("timezone"),
            "ticket_class": obj.get("ticket_class"),
            "name": obj.get("name"),
            "event_end_at": obj.get("event_end_at"),
            "delivery_mode": obj.get("delivery_mode"),
            "venue_name": obj.get("venue_name"),
            "venue_address": obj.get("venue_address"),
            "seating": TicketSeating.from_dict(obj["seating"]) if obj.get("seating") is not None else None,
            "terms_url": obj.get("terms_url"),
            "attendee_required": obj.get("attendee_required")
        })
        return _obj


